package edams.comm;

public class CommVars {

	/**
	 * 날짜시간 포맷 패턴.
	 */
	public static String[] dateFormatPattern = {
		"yyyy.MM.dd'T'HH:mm:ss:SSS a, z",
		"yyyy.MM.dd'T'HH:mm:ss.SSS a, z",
		"yyyy.MM.dd'T'HH:mm:ss a, z",
		"yyyy-MM-dd'T'HH:mm:ss:SSS a, z",
		"yyyy-MM-dd'T'HH:mm:ss.SSS a, z",
		"yyyy-MM-dd'T'HH:mm:ss a, z",
		"yyyy/MM/dd'T'HH:mm:ss:SSS a, z",
		"yyyy/MM/dd'T'HH:mm:ss.SSS a, z",
		"yyyy/MM/dd'T'HH:mm:ss a, z",
		"yyyyMMdd'T'HH:mm:ss:SSS a, z",
		"yyyyMMdd'T'HH:mm:ss.SSS a, z",
		"yyyyMMdd'T'HH:mm:ss a, z",
		"yyyyMMdd'T'HHmmss.SSS a, z",
		"yyyyMMdd'T'HHmmssSSS a, z",
		"yyyyMMdd'T'HHmmss a, z",
		"yyyy.MM.dd'T'HH:mm a, z",
		"yyyy.MM.dd'T'HH a, z",
		"yyyy-MM-dd'T'HH:mm a, z",
		"yyyy-MM-dd'T'HH a, z",
		"yyyy/MM/dd'T'HH:mm a, z",
		"yyyy/MM/dd'T'HH a, z",
		"yyyyMMdd'T'HH:mm a, z",
		"yyyyMMdd'T'HHmm a, z",
		"yyyyMMdd'T'HH a, z",
		"yyyy.MM.dd'T'HH:mm:ss:SSSZ",
		"yyyy.MM.dd'T'HH:mm:ss.SSSZ",
		"yyyy.MM.dd'T'HH:mm:ssZ",
		"yyyy-MM-dd'T'HH:mm:ss:SSSZ",
		"yyyy-MM-dd'T'HH:mm:ss.SSSZ",
		"yyyy-MM-dd'T'HH:mm:ssZ",
		"yyyy/MM/dd'T'HH:mm:ss:SSSZ",
		"yyyy/MM/dd'T'HH:mm:ss.SSSZ",
		"yyyy/MM/dd'T'HH:mm:ssZ",
		"yyyyMMdd'T'HH:mm:ss:SSSZ",
		"yyyyMMdd'T'HH:mm:ss.SSSZ",
		"yyyyMMdd'T'HH:mm:ssZ",
		"yyyyMMdd'T'HHmmss.SSSZ",
		"yyyyMMdd'T'HHmmssSSSZ",
		"yyyyMMdd'T'HHmmssZ",
		"yyyy.MM.dd'T'HH:mmZ",
		"yyyy.MM.dd'T'HHZ",
		"yyyy-MM-dd'T'HH:mmZ",
		"yyyy-MM-dd'T'HHZ",
		"yyyy/MM/dd'T'HH:mmZ",
		"yyyy/MM/dd'T'HHZ",
		"yyyyMMdd'T'HH:mmZ",
		"yyyyMMdd'T'HHmmZ",
		"yyyyMMdd'T'HHZ",
		"yyyy.MM.dd'T'HH:mm:ss:SSS z",
		"yyyy.MM.dd'T'HH:mm:ss.SSS z",
		"yyyy.MM.dd'T'HH:mm:ss z",
		"yyyy-MM-dd'T'HH:mm:ss:SSS z",
		"yyyy-MM-dd'T'HH:mm:ss.SSS z",
		"yyyy-MM-dd'T'HH:mm:ss z",
		"yyyy/MM/dd'T'HH:mm:ss:SSS z",
		"yyyy/MM/dd'T'HH:mm:ss.SSS z",
		"yyyy/MM/dd'T'HH:mm:ss z",
		"yyyyMMdd'T'HH:mm:ss:SSS z",
		"yyyyMMdd'T'HH:mm:ss.SSS z",
		"yyyyMMdd'T'HH:mm:ss z",
		"yyyyMMdd'T'HHmmss.SSS z",
		"yyyyMMdd'T'HHmmssSSS z",
		"yyyyMMdd'T'HHmmss z",
		"yyyy.MM.dd'T'HH:mm z",
		"yyyy.MM.dd'T'HH z",
		"yyyy-MM-dd'T'HH:mm z",
		"yyyy-MM-dd'T'HH z",
		"yyyy/MM/dd'T'HH:mm z",
		"yyyy/MM/dd'T'HH z",
		"yyyyMMdd'T'HH:mm z",
		"yyyyMMdd'T'HHmm z",
		"yyyyMMdd'T'HH z",
		"yyyy.MM.dd'T'HH:mm:ss:SSS a",
		"yyyy.MM.dd'T'HH:mm:ss.SSS a",
		"yyyy.MM.dd'T'HH:mm:ss a",
		"yyyy-MM-dd'T'HH:mm:ss:SSS a",
		"yyyy-MM-dd'T'HH:mm:ss.SSS a",
		"yyyy-MM-dd'T'HH:mm:ss a",
		"yyyy/MM/dd'T'HH:mm:ss:SSS a",
		"yyyy/MM/dd'T'HH:mm:ss.SSS a",
		"yyyy/MM/dd'T'HH:mm:ss a",
		"yyyyMMdd'T'HH:mm:ss:SSS a",
		"yyyyMMdd'T'HH:mm:ss.SSS a",
		"yyyyMMdd'T'HH:mm:ss a",
		"yyyyMMdd'T'HHmmss.SSS a",
		"yyyyMMdd'T'HHmmssSSS a",
		"yyyyMMdd'T'HHmmss a",
		"yyyy.MM.dd'T'HH:mm a",
		"yyyy.MM.dd'T'HH a",
		"yyyy-MM-dd'T'HH:mm a",
		"yyyy-MM-dd'T'HH a",
		"yyyy/MM/dd'T'HH:mm a",
		"yyyy/MM/dd'T'HH a",
		"yyyyMMdd'T'HH:mm a",
		"yyyyMMdd'T'HHmm a",
		"yyyyMMdd'T'HH a",
		"yyyy.MM.dd'T'HH:mm:ss:SSS",
		"yyyy.MM.dd'T'HH:mm:ss.SSS",
		"yyyy.MM.dd'T'HH:mm:ss",
		"yyyy-MM-dd'T'HH:mm:ss:SSS",
		"yyyy-MM-dd'T'HH:mm:ss.SSS",
		"yyyy-MM-dd'T'HH:mm:ss",
		"yyyy/MM/dd'T'HH:mm:ss:SSS",
		"yyyy/MM/dd'T'HH:mm:ss.SSS",
		"yyyy/MM/dd'T'HH:mm:ss",
		"yyyyMMdd'T'HH:mm:ss:SSS",
		"yyyyMMdd'T'HH:mm:ss.SSS",
		"yyyyMMdd'T'HH:mm:ss",
		"yyyyMMdd'T'HHmmss.SSS",
		"yyyyMMdd'T'HHmmssSSS",
		"yyyyMMdd'T'HHmmss",
		"yyyy.MM.dd'T'HH:mm",
		"yyyy.MM.dd'T'HH",
		"yyyy-MM-dd'T'HH:mm",
		"yyyy-MM-dd'T'HH",
		"yyyy/MM/dd'T'HH:mm",
		"yyyy/MM/dd'T'HH",
		"yyyyMMdd'T'HH:mm",
		"yyyyMMdd'T'HHmm",
		"yyyyMMdd'T'HH",
		"yyyy.MM.dd HH:mm:ss:SSS a, z",
		"yyyy.MM.dd HH:mm:ss.SSS a, z",
		"yyyy.MM.dd HH:mm:ss a, z",
		"yyyy-MM-dd HH:mm:ss:SSS a, z",
		"yyyy-MM-dd HH:mm:ss.SSS a, z",
		"yyyy-MM-dd HH:mm:ss a, z",
		"yyyy/MM/dd HH:mm:ss:SSS a, z",
		"yyyy/MM/dd HH:mm:ss.SSS a, z",
		"yyyy/MM/dd HH:mm:ss a, z",
		"yyyyMMdd HH:mm:ss:SSS a, z",
		"yyyyMMdd HH:mm:ss.SSS a, z",
		"yyyyMMdd HH:mm:ss a, z",
		"yyyyMMdd HHmmss.SSS a, z",
		"yyyyMMdd HHmmssSSS a, z",
		"yyyyMMdd HHmmss a, z",
		"yyyy.MM.dd HH:mm a, z",
		"yyyy.MM.dd HH a, z",
		"yyyy-MM-dd HH:mm a, z",
		"yyyy-MM-dd HH a, z",
		"yyyy/MM/dd HH:mm a, z",
		"yyyy/MM/dd HH a, z",
		"yyyyMMdd HH:mm a, z",
		"yyyyMMdd HHmm a, z",
		"yyyyMMdd HH a, z",
		"yyyy.MM.dd HH:mm:ss:SSSZ",
		"yyyy.MM.dd HH:mm:ss.SSSZ",
		"yyyy.MM.dd HH:mm:ssZ",
		"yyyy-MM-dd HH:mm:ss:SSSZ",
		"yyyy-MM-dd HH:mm:ss.SSSZ",
		"yyyy-MM-dd HH:mm:ssZ",
		"yyyy/MM/dd HH:mm:ss:SSSZ",
		"yyyy/MM/dd HH:mm:ss.SSSZ",
		"yyyy/MM/dd HH:mm:ssZ",
		"yyyyMMdd HH:mm:ss:SSSZ",
		"yyyyMMdd HH:mm:ss.SSSZ",
		"yyyyMMdd HH:mm:ssZ",
		"yyyyMMdd HHmmss.SSSZ",
		"yyyyMMdd HHmmssSSSZ",
		"yyyyMMdd HHmmssZ",
		"yyyy.MM.dd HH:mmZ",
		"yyyy.MM.dd HHZ",
		"yyyy-MM-dd HH:mmZ",
		"yyyy-MM-dd HHZ",
		"yyyy/MM/dd HH:mmZ",
		"yyyy/MM/dd HHZ",
		"yyyyMMdd HH:mmZ",
		"yyyyMMdd HHmmZ",
		"yyyyMMdd HHZ",
		"yyyy.MM.dd HH:mm:ss:SSS z",
		"yyyy.MM.dd HH:mm:ss.SSS z",
		"yyyy.MM.dd HH:mm:ss z",
		"yyyy-MM-dd HH:mm:ss:SSS z",
		"yyyy-MM-dd HH:mm:ss.SSS z",
		"yyyy-MM-dd HH:mm:ss z",
		"yyyy/MM/dd HH:mm:ss:SSS z",
		"yyyy/MM/dd HH:mm:ss.SSS z",
		"yyyy/MM/dd HH:mm:ss z",
		"yyyyMMdd HH:mm:ss:SSS z",
		"yyyyMMdd HH:mm:ss.SSS z",
		"yyyyMMdd HH:mm:ss z",
		"yyyyMMdd HHmmss.SSS z",
		"yyyyMMdd HHmmssSSS z",
		"yyyyMMdd HHmmss z",
		"yyyy.MM.dd HH:mm z",
		"yyyy.MM.dd HH z",
		"yyyy-MM-dd HH:mm z",
		"yyyy-MM-dd HH z",
		"yyyy/MM/dd HH:mm z",
		"yyyy/MM/dd HH z",
		"yyyyMMdd HH:mm z",
		"yyyyMMdd HHmm z",
		"yyyyMMdd HH z",
		"yyyy.MM.dd HH:mm:ss:SSS a",
		"yyyy.MM.dd HH:mm:ss.SSS a",
		"yyyy.MM.dd HH:mm:ss a",
		"yyyy-MM-dd HH:mm:ss:SSS a",
		"yyyy-MM-dd HH:mm:ss.SSS a",
		"yyyy-MM-dd HH:mm:ss a",
		"yyyy/MM/dd HH:mm:ss:SSS a",
		"yyyy/MM/dd HH:mm:ss.SSS a",
		"yyyy/MM/dd HH:mm:ss a",
		"yyyyMMdd HH:mm:ss:SSS a",
		"yyyyMMdd HH:mm:ss.SSS a",
		"yyyyMMdd HH:mm:ss a",
		"yyyyMMdd HHmmss.SSS a",
		"yyyyMMdd HHmmssSSS a",
		"yyyyMMdd HHmmss a",
		"yyyy.MM.dd HH:mm a",
		"yyyy.MM.dd HH a",
		"yyyy-MM-dd HH:mm a",
		"yyyy-MM-dd HH a",
		"yyyy/MM/dd HH:mm a",
		"yyyy/MM/dd HH a",
		"yyyyMMdd HH:mm a",
		"yyyyMMdd HHmm a",
		"yyyyMMdd HH a",
		"yyyy.MM.dd HH:mm:ss:SSS",
		"yyyy.MM.dd HH:mm:ss.SSS",
		"yyyy.MM.dd HH:mm:ss",
		"yyyy-MM-dd HH:mm:ss:SSS",
		"yyyy-MM-dd HH:mm:ss.SSS",
		"yyyy-MM-dd HH:mm:ss",
		"yyyy/MM/dd HH:mm:ss:SSS",
		"yyyy/MM/dd HH:mm:ss.SSS",
		"yyyy/MM/dd HH:mm:ss",
		"yyyyMMdd HH:mm:ss:SSS",
		"yyyyMMdd HH:mm:ss.SSS",
		"yyyyMMdd HH:mm:ss",
		"yyyyMMdd HHmmss.SSS",
		"yyyyMMdd HHmmssSSS",
		"yyyyMMdd HHmmss",
		"yyyy.MM.dd HH:mm",
		"yyyy.MM.dd HH",
		"yyyy-MM-dd HH:mm",
		"yyyy-MM-dd HH",
		"yyyy/MM/dd HH:mm",
		"yyyy/MM/dd HH",
		"yyyyMMdd HH:mm",
		"yyyyMMdd HHmm",
		"yyyyMMdd HH",
		"yyyy.MM.dd",
		"yyyy-MM-dd",
		"yyyy/MM/dd",
		"yyyyMMdd"
	};
}
